---
- hosts: infra
  tasks:
    
    - name: generate key pair for root on localhost
      user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

    - name: fetch public key
      fetch:
        src: /root/.ssh/id_rsa.pub
        dest: tmp/
        flat: yes

- hosts: all
  tasks:

    - name: add root public key to other servers
      authorized_key:
        user: root
        key: "{{ lookup('file', 'tmp/id_rsa.pub') }}"
