- name: Get service on port 4000
  shell: netstat -tulpen | grep ":4000 " | sed -e 's/.*\///'
  register: command_result

- name: Create registry on deploy host
  delegate_to: "{{item}}"
  with_items: "{{groups['infra']}}"
  command: docker run -d -p 4000:5000 --restart=always --name registry registry:2
  when: command_result.stdout != "docker-proxy" 
